### ISSUE TITLE
Switching out of chat is nonintuitive.

### ISSUE THREAD

**Issue by Tekkraft** [64bitpandas/AtomBlast.io#10]
When you try to switch out of the chat box, you can't click in the game area to exit the chat mode. It's not gamebreakinig, but it could be improved upon.

**Comment by 64bitpandas** [comment]
I can't reproduce this, clicking out works fine for me.
However I also discovered that if you try to press escape while in chat, it will open up the menu instead of exiting the chatbox, which is also very unintuitive.

**Comment by 64bitpandas** [comment]
This issue was moved to BananiumLabs/AtomBlast.io#10
