### ISSUE TITLE
Movement bug when switching windows

### ISSUE THREAD

**Issue by Kuxxe** [64bitpandas/AtomBlast.io#14]
When holding one or more of the movement buttons (WASD) and switching to a different window, it keeps moving even when not interacting with atomblast. 

When switching back to atomblast, the movement persists until the movement buttons are pressed again.

(I think this might be caused by the game still thinking the buttons are pressed even when there is no interaction)

**Comment by DarkFlamex1** [comment]
Is this a duplicate of #9 ? Will attempt to reproduce?

**Comment by DarkFlamex1** [comment]
Was able to successfully reproduce, I have achieved a fix in the next commit.
I manually set the movement keys to key up when the document loses focus as shown below.

```
for(let key in moveKeys){
      moveKeys[key].isDown = false;
      moveKeys[key].isUp = true;
}
```

**Comment by 64bitpandas** [comment]
This issue was moved to BananiumLabs/AtomBlast.io#14
