### ISSUE TITLE
Basic Interaction Between Players (Compounds)

### ISSUE THREAD

**Issue by EnumC** [64bitpandas/AtomBlast.io#16]
Implement the following from game concept
![screen shot 2018-07-08 at 7 22 26 pm](https://user-images.githubusercontent.com/5799869/42427661-a2269104-82e4-11e8-9d4b-b3b166858f54.png)

Elements: Hydrogen, Oxygen, Carbon, Chlorine, Nitrogen, Uranium, Iron
Classes:
Basic: Can be shot like a projectile. Dissolves on contact with any other compound or player.
Reactive: Destroys any compounds it collides with - does not stop! (Priority over Explosive and Suppressive, but NOT Nuclear)
Suppressive: Reduces movement speed of players hit.
Acidic: Deals damage over time to players.
Explosive: Explodes on contact with compound or player.
Defensive: Lowers damage taken from hits.
Nuclear: Explodes, and leaves radiation if it collides with another Nuclear particle.
Magnetic: Moves towards other Magnetic particles.
Ionic: Moves away from other Ionic particles. Moves towards Magnetic particles.

**Comment by 64bitpandas** [comment]
This issue was moved to BananiumLabs/AtomBlast.io#16
