### ISSUE TITLE
Health System

### ISSUE THREAD

**Issue by DarkFlamex1** [64bitpandas/AtomBlast.io#2]
Creation of a basic health system is required.

- A simple variable in the player object

- Should sync over the network

**Comment by DarkFlamex1** [comment]
Created Health System in https://github.com/BananiumLabs/AtomBlast.io/commit/c1be467d5df1d6d99c68b188c40d3def3b94e4a3

Syncs the health of a player of the network but should test the damage function before considering the system complete.

**Comment by 64bitpandas** [comment]
This issue was moved to BananiumLabs/AtomBlast.io#2
