### ISSUE TITLE
Atom Enhancement

### ISSUE THREAD

**Issue by MuaazWahid** [64bitpandas/AtomBlast.io#22]
Instead of playing as a particle, players play as an atom, and as they destroy other players, they gain electrons. After gaining a certain amount of electrons, the player upgrades to the next atom in the periodic table. For example, a player starts as a hydrogen atom, then after defeating a certain amount of players, they upgrade to helium, then after defeating a certain amount of players, they upgrade to lithium, and so on. As they progress it gets harder and harder for them to play (slower movement, slower projectiles, etc.). This is so that no one player gets too strong, and keeps the power in check among the players.

**Comment by 64bitpandas** [comment]
This issue was moved to BananiumLabs/AtomBlast.io#22
