### ISSUE TITLE
Casual MOBA Idea

### ISSUE THREAD

**Issue by 64bitpandas** [64bitpandas/AtomBlast.io#24]
What we DON'T want.
 - A battle royale / Fortnite clone.
 - Something only fun if a large amount of players (50-100) are in a server at the same time.
 - Something overly complex, either mechanically or graphically.

What we DO want.
 - Something unique.
 - Something that can be enjoyed both individually and as a small team.
 - Something that is casual and can be picked up instantly, but be nuanced enough to get players to keep coming back for more.

My proposed solution:
 - Take some elements from MOBA (smaller, defined map size with consistent and understandable objectives) without pressing the intense team-based atmosphere often associated with them.
 - Make games for a small number of players (8-10, or 2-4 teams) for a small amount of time (5-10 minutes max).
 - Whoever gets the most kills wins. Kills are defined by whoever did the most damage, in order to prevent killstealing.
 - Objectives will give more atoms, or boost your stats (health, defense, damage, etc). You can also pick up legendary blueprints (an idea suggested by @JeffY95014 ) which last throughout the game but cannot be used in later games.
 - Use level system that MOBAs have (as suggested by @MuaazWahid ) so the more kills/objectives you take, the higher the level you are. We could even allow people to unlock more blueprint slots as you get higher level? Just an idea.

Comments about this idea are very appreciated.

**Comment by Tekkraft** [comment]
I like the idea, but there are some refinements that should be made.

1. UI Changes: Teams should be randomly set, or premade. The text input should be removed.
2. Matchmaking: Rooms should follow teams - randomly set, or premade. No text input.
3. Map design: The map, objectives, and atom sources should be balanced.
4. XP: If we are going to have xp, we should have player types. Not necessarily individual characters, more like adaptations, such as less damage for more health, less speed for a smaller hitbox, etc. More slots might not be feasible, given the nature of out-of-game kit selection.

Further notes: A good method would be options for: 2 teams of 4 and 6 minutes, 4 teams of 2 and 4 minutes, or 4 teams of 4 and 10 minutes. Numbers are subject to change.

**Comment by 64bitpandas** [comment]
1. Definitely, that would also get rid of an input box to make things simpler on the main menu.
2 and 3 - We would have 2 maps, one for 2 teams and one for 4 teams. Each half or quadrant would have identical resources, and then the most powerful resources would be in the middle for people to fight over.
4 - We will probably have two xp systems, one ingame and one out of game. The one out of game will be only used for unlocking blueprints, visuals, and other non-game-impacting perks. The one in game will reset each round, like a standard MOBA, and increase your stats/buffs.

**Comment by 64bitpandas** [comment]
This issue was moved to BananiumLabs/AtomBlast.io#24
