### ISSUE TITLE
Player Stays on Disconnect

### ISSUE THREAD

**Issue by DarkFlamex1** [64bitpandas/AtomBlast.io#3]
For some unknown reason when someone disconnects(Randomly not planned) the player that left is still left in the room. The image below illustrates the issue.

![image](https://user-images.githubusercontent.com/8906527/42179261-166fca28-7de8-11e8-9945-05e58d984046.png)

The image below shows the disconnected screen after disconnecting rapidly.

![image](https://user-images.githubusercontent.com/8906527/42179287-2ac0511e-7de8-11e8-851b-af5299a40a7c.png)

The log below shows the server log during this time frame.

> [Server] Setting up room room
{ id: 'ziaAmLYUbF8U-C8LAAAC',
  name: 'muaaz',
  room: 'room',
  team: 'blue',
  health: 100,
  posX: 0,
  posY: 0,
  vx: 0,
  vy: 0 }
[Server] Player muaaz (ziaAmLYUbF8U-C8LAAAC) joined room room in team blue
{ id: '-tCnHhZ5lui2C8rNAAAD',
  name: 'abc',
  room: 'room',
  team: 'ab',
  health: 100,
  posX: 0,
  posY: 0,
  vx: 0,
  vy: 0 }
[Server] Player abc (-tCnHhZ5lui2C8rNAAAD) joined room room in team ab
Disconnect Received: ping timeout

**Comment by DarkFlamex1** [comment]
The fix for this bug will be implemented after we finish the other outstanding bug in https://github.com/BananiumLabs/AtomBlast.io/issues/4

**Comment by DarkFlamex1** [comment]
Fixed in commit https://github.com/BananiumLabs/AtomBlast.io/commit/c976f7b1fadcb69fb1fa0bd3ef1f3411857ac2e1

**Comment by 64bitpandas** [comment]
This issue was moved to BananiumLabs/AtomBlast.io#3
