### ISSUE TITLE
Previously Connected Players Not Created

### ISSUE THREAD

**Issue by DarkFlamex1** [64bitpandas/AtomBlast.io#4]
This issue was discovered during a fix for the disconnect.

Some information regarding the issue is stated below. Also the images were taken **after both players joined the room.**

This player is the first person to join the room(Image below):
![image](https://user-images.githubusercontent.com/8906527/42181670-74cef88e-7df0-11e8-87db-328cbe46db7e.png)
Notice how the chat shows that the 2nd player has joined the room...

This player is the second player to join the room(Image Below):
![image](https://user-images.githubusercontent.com/8906527/42181684-8e304aee-7df0-11e8-8632-f92e8660dd76.png)

The second player works fine but cannot see the third player.

This is the third player to join the room:
![image](https://user-images.githubusercontent.com/8906527/42181701-a18f725e-7df0-11e8-9a6a-793013f2f0c2.png)

And so on....

The related code snippet regarding this issue is:
~~~
// Does not exist - need to create new player
else if (isSetup && (players[socket.id] === undefined || players[socket.id] === null)){
      console.log("Create a player");
      players[player] = createPlayer(pl);
}
~~~
The snippet is located in app.js from lines 175 to 180.

Both statements in this OR statement return false ``` (players[socket.id] === undefined || players[socket.id] === null)``` for the player who joined before.

**Comment by 64bitpandas** [comment]
This issue was moved to BananiumLabs/AtomBlast.io#4
