### ISSUE TITLE
Team System

### ISSUE THREAD

**Issue by EnumC** [64bitpandas/AtomBlast.io#7]
Team system backbone for multiplayer gameplay - 

Implement: 
1) Create team input field and emit value

2) Create value for player for future reference

3) Functional team/non-team differentiation

**Comment by DarkFlamex1** [comment]
Maybe we can create a minimap where you can see your teammates, or indicators on the screen that point in the direction of your team.

**Comment by 64bitpandas** [comment]
This issue was moved to BananiumLabs/AtomBlast.io#7
