### ISSUE TITLE
Player continues to move if they enter chat menu while moving.

### ISSUE THREAD

**Issue by Tekkraft** [64bitpandas/AtomBlast.io#9]
During a test, I found that holding down a key and then clicking in the chat menu will keep a player moving in the direction they were last moving with no slowdown.

**Comment by EnumC** [comment]
This could also be reproduced if you unfocus the window.

**Comment by EnumC** [comment]
Fixed.

**Comment by 64bitpandas** [comment]
This issue was moved to BananiumLabs/AtomBlast.io#9
